name: WaysOfSuccess
favicon: null
layout_spectrum: 0.49366
typography_spectrum: 0.60493
title: Learn about our Ways of Success
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#667884'
    - '#202d33'
    - '#cccfd4'
    - '#eda20d'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
