name: WaysOfSuccess
favicon: null
layout_spectrum: 0.50865
typography_spectrum: 0.75858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#e1e1e1'
    - '#303030'
    - '#b5b5b5'
    - '#7d7d7d'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
