name: WaysOfSuccess
favicon: null
layout_spectrum: 0.13873
typography_spectrum: 0.39097
title: Learn about our Ways of Success
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#e1e1e1'
    - '#303030'
    - '#b5b5b5'
    - '#7d7d7d'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
